# Change these first
owner: worick # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: HealingTour
    url: https://www.healingtour.com
  - name: Jhferry
    url: https://www.jhferry.com
  - name: ATNSoft
    url: http://atnsoft.co.kr/
  - name: DEMO
    url: http://demo.atnsoft.co.kr
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Web Status"
  introMessage: 서버상태확인
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
